version: "2"
services:
    rabbitmq:
      image: "rabbitmq:latest"
      hostname: "rabbitmq"
      environment:
        RABBITMQ_ERLANG_COOKIE: "SADOSAIQRRQOQ"
        RABBITMQ_DEFAULT_USER: "guest"
        RABBITMQ_DEFAULT_PASS: "guest"
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - "15672:15672"
        - "5672:5672"
      labels:
        NAME: "rabbitmq"
      volumes:
        - "~/docker/data/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

networks:
  default:
    external:
      name: devtest

      