version: "2"
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
    - "~/docker/data/mongodb:/data"
    ports:
    - "27017:27017"
    
networks:
  default:
    external:
      name: devtest

