version: "2"
services:
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    restart: always
    ports:
      - "9200:9200"
    networks:
      default:
        aliases:
          - elasticsearch
    volumes:
      - "~/docker/data/elasticsearch/:/usr/share/elasticsearch/data"

               
networks:
  default:
    external:
      name: devtest

