version: "3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0-arm64
    container_name: b-elastic
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
      - xpack.security.enabled=false
    volumes:
      - ./:/project
    ports:
      - 9200:9200
               

