version: "2"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    restart: always
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://esforcontent:9200"
    networks:
      default:
        aliases:
          - kibana
 
networks:
  default:
    external:
      name: devtest

