version: "2"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      default:
        aliases:
          - jenkins
    volumes:
      - "~/docker/data/jenkins:/var/jenkins_home"
          
networks:
  default:
    external:
      name: devtest

