version: "2"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      SA_PASSWORD: "ThePasswordForS@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - "~/docker/data/sqlserver:/var/opt/mssql"    
    networks:
      default:
        aliases:
          - sqlserver
          
networks:
  default:
    external:
      name: devtest

