version: "2"
services:
    apigateway:
        image: shahedk/apigateway:latest
        restart: always
        volumes:
          - "~/docker/config/apigateway/appsettings.json:/app/appsettings.json"
          - "~/docker/data/apigateway/db/:/app/db/"
        ports:
          - "8090:80"
networks:
  default:
    external:
      name: devtest