version: "2"
services:
    apigateway:
        container_name: apigateway
        image: shahedk/apigateway:latest
        restart: always
        networks:
          default:
            aliases:
              - apigateway
        volumes:
          - "~/docker/config/apigateway/appsettings.json:/app/appsettings.json"
          - "~/docker/data/apigateway/db/:/app/db/"
        
networks:
  default:
    external:
      name: devtest